apiVersion: v1
kind: Service
metadata:
  namespace: rec-sys-namespace
  name: rec-sys-service
  labels:
    app-label: rec-sys-app-label
spec:
  ports:
    - port: 80
      name: http
      targetPort: 80
  selector:
    app-label: rec-sys-app-label
  type: LoadBalancer

