apiVersion: v1
kind: Service
metadata:
  namespace: rec-sys-namespace
  name: rec-sys-service
  labels:
    app-label: rec-sys-app-label
spec:
  ports:
    - name: animeserviceport
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app-label: rec-sys-app-label
  type: LoadBalancer

